### ISSUE TITLE
support for Page Visibility API aka window blur/focus aka "I leave a tab in background"

### ISSUE THREAD

**Issue by gre** [brigade/react-waypoint#194]
I think this library would be great if it would also provide the "onLeave" behavior when the document becomes "invisible", for instance you changed the tab on your browser, or you minimized the window and call back the "onEnter" when it comes back to visibility. there seems to be an API for that https://www.w3.org/TR/page-visibility/ but i'm pretty sure a way to detect that existed for a lot of time, back in the days i remember using `jQuery(window).blur(fn)` and `focus(fn)` a lot for this.. it is really useful if you don't want to leave tab running animation in background. even tho, nowadays, browser should schedule less timer events/animation frames when in background it's still some useless interval/animations calls that can potentially be saved with this.

I imagine this can be an opt-in behavior because maybe this does not make sense for all usages of Waypoint, but I still think it should be part of the library for a unified way to handle onEnter/onLeave logics.

**Comment by gre** [comment]
(also just want to thanks you for this great library! really like library like these that exclusively focus on solving one complex problem)

**Comment by jmeas** [comment]
Hi @gre! Thanks for sharing your idea to improve this library!

I'm always open to considering how this library can be improved, but I might need a bit more information to see the value in this addition.

For instance, consider a page that has 200 Waypoints. If i wanted to add some page visibility logic here, I'm thinking I'd want to have that in 1 central place rather than in my 200 Waypoints. Perhaps a single utility that updates a central store (like redux) for instance. Since I only need a single place to track this global state, it seems unusual that I would select just one of those 200 Waypoints as the one responsible for this.

Or, perhaps I have another page that has no locations I'd want to use a Waypoint for, but I do want to track page visibility. Adding a Waypoint to the page for the purpose of getting the page visibility callback also seems strange to me.

I agree that tracking page visibility is useful, and I also think that Waypoints are useful. The part I'm missing is how combining the two into one library provides a unique benefit over keeping them separate. It's entirely possible that I'm missing something obvious though. Would you have time to try and elaborate a bit further? I'd really appreciate it!

**Comment by levibuzolic** [comment]
This is also a feature that I'd find useful, in my case I'm using `react-waypoint` to start/stop/replay some animations that occur as you scroll through different parts of a site. I've implemented my own window focus tracking to handle this, but it'd be convenient if `react-waypoint` had this feature.

I can see how this feature is a little unrelated to `react-waypoint` but there certainly is some overlap in use cases.

Potentially it could be opt-in via a prop like `trackWindowFocus`.

Anyway, thanks for a great library. 👌

**Comment by jmeas** [comment]
Hi @levibuzolic ! Thanks for adding more info to this issue about your use case. I’ve thought more about this, though, and I’m still not too convinced that it makes sense to merge it in here. Window focus state is global state, yet waypoints are individual bits of localized state, _within_ a given window. This difference in scope just suggests to me that it doesn’t make sense to add this feature to this library. Waypoints are all about scroll position, and not window focus state.

I think it’s better for this library to stay scoped to solving one specific issue (related to scroll position), and not branch out to cover other aspects of window state.

I’m going to close this out for now, but that doesn’t mean that the conversation has to end here. If you, or anyone else, wants to try to make additional arguments in favor for this feature, definitely do so. Also, @trotzig / @lencioni feel free to chime in/reopen if you feel differently.

Thanks, and sorry!

**Comment by levibuzolic** [comment]
@jmeas that sounds absolutely fair, while there's overlap in use, it's definitely a bit outside the scope of this library. Thanks for taking the time. :+1:
